### ISSUE TITLE
[contenthash] & [hash] doesn't seem to work with 'styles' option

### ISSUE THREAD

**Issue by redandblackstar** [cascornelissen/svg-spritemap-webpack-plugin#53]
When also generating a CSS file [contenthash] & [hash] doesn't seem to work!

```
...
styles : {
	filename : 'my-css-[hash].css'
}
...
```

- i have tried it with both 3.0.0-rc.2 and 2.7.1 and they both generate the file but do not add [contenthash] & [hash]...for example they just output a file like this -> my-css-[hash].css (with the literal [hash] text)

- [contenthash] & [hash] works OK when using it for the SVG option
```
...
output : {
	filename : 'spritemap-[contenthash].svg'
}
...
```

**Comment by cascornelissen** [comment]
@redandblackstar, thanks for the report; I'll look into this when I have the time and I'll make sure it gets fixed before the first stable `3.0.0` version. If you have the time to look into it, you're free to submit a PR of course.

**Comment by cascornelissen** [comment]
@redandblackstar, thanks once more for the bug report. I've fixed this in `master`, could you install directly from GitHub and check if this solves the issue on your side as well?

```
npm install cascornelissen/svg-spritemap-webpack-plugin#master
```

Thanks in advance!

**Comment by redandblackstar** [comment]
Amazing! I will check this soon! THANK YOU!

**Comment by redandblackstar** [comment]
I requested master (I am using yarn) and it gives me choices on what to choose:

❯ 3.0.0-rc.2 
  3.0.0-rc.1 
  2.7.1 
  2.7.0 

I tried both 3.0.0-rc.2 &  3.0.0-rc.1  but they do not work for me. I also just tried looking at the commit you made i believe its only in one file inside the lib folder (index.js). I manually applied this change just to test on my node modules folder but it still doesnt work!

`if ( typeof this.styles === 'undefined' || this.stylesType !== 'asset' )`

Additionally, not sure if you have any advice on this but I am using a plugin called "Webpack Manifest Plugin" and when I was using the "2.7.1" version of "svg-spritemap-webpack-plugin" it would add the generated SVG (wouldn't work with the generated css file) automatically but now with "3.0." it doesnt add it at all. At any rate with any of these versions I still see the output generate just the string "[hash]" or "[contenthash]"

**Comment by cascornelissen** [comment]
Ah, I finally noticed what's going on. You're using the asset notation (first bullet in the [`styles.filename` documentation](https://github.com/cascornelissen/svg-spritemap-webpack-plugin/blob/master/docs/options.md#stylesfilename--spritescss)) which adds the styles file as a webpack asset and webpack should replace the strings with the hashes. I'll have to look into what's going wrong in this very specific use case.

And when this gets fixed in `master`, you can use the following command for Yarn to install from the branch:

```
yarn add https://github.com/cascornelissen/svg-spritemap-webpack-plugin#master
```

**Comment by redandblackstar** [comment]
Thank you for the reply!

Ill try it out once there is an update and ill look into submitting more detail for the other issue related to the "Webpack Manifest Plugin"

**Comment by cascornelissen** [comment]
@redandblackstar, could you test this with the current `master` release? I can't seem to reproduce your problem using any of the following configurations (both hashes get added correctly).

```
new SVGSpritemapPlugin('src/**/*.svg', {
    styles: 'test.[hash].[contenthash].css'
})
```
```
new SVGSpritemapPlugin('src/**/*.svg', {
    styles: {
        filename: 'test.[hash].[contenthash].css'
    }
})
```

**Comment by cascornelissen** [comment]
ping @redandblackstar

**Comment by cascornelissen** [comment]
Just verified I still can't reproduce this on `master`, I'm closing the issue as I want to finish the milestone and release `3.0.0`.

**Comment by groomain** [comment]
Hi,

With the 3.0.0 version my manifest json look like this 

"build/svg/icons.59cf10a6f7abb6fad7fd.svg": "/build/svg/icons.59cf10a6f7abb6fad7fd.svg"

any ideas why ?
my config : 
new SvgStorePlugin("svg/**/*.svg", {
      output: {
        chunk: { name: "svg/icons" },
        filename: "svg/icons.[hash].svg",
        svgo: true
      },
      sprite: {
        prefix: "icon-",
      }
    })

Thanks !

**Comment by cascornelissen** [comment]
@groomain, this seems to be unrelated to the original issue. Would you mind creating a new issue and providing a little more information (Webpack version, what you expect to happen, did it work in the `2.x` release, etc.)
